demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("project.urls")),
    # path('admin/', admin.site.urls),
]

demo/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views


app_name = 'project'
urlpatterns = [
    path('list/<container_name>/', views.container_detail, name="container_detail"),
    path('containers/', views.container_list, name="container"),
    path('add_container/', views.add_container, name="add_container"),
    path('remove_container/', views.remove_container, name="remove_container"),
    path('remove_container_content/', views.remove_container_content, name="remove_container_content"),
    path('upload/<container_name>/', views.add_container_content, name="add_container_content"),
    path('download/<container_name>/<file_name>/', views.get_content_temp_url, name="get_content_temp_url"),
    path('', views.index, name="index"),
    path('logout/', views.logout, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo/project/models.py
from django.db import models

# Create your models here.

demo/project/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .adapter import *

def index(request):
    if request.method == "GET":
        return render(request, 'project/index.html')
    elif request.method == "POST":
        project_name = request.POST['project_name']
        user_name = request.POST['user_name']
        password = request.POST['password']
        token = login(user_name, password, project_name)
        request.session["token"] = token
        if token:
            return HttpResponseRedirect(reverse('project:container'))
        else:
            error_msg = "Wrong Combination of username and password"
            messages.error(request, error_msg)
            return HttpResponseRedirect(reverse('project:index'))


def logout(request):
    if request.method == "POST":
        request.session['token'] = None
        return HttpResponseRedirect(reverse('project:index'))


def container_list(request):
    if request.method == "GET" and request.session["token"]:
        # 账号密码验证
        containers_list = get_containers_list(request.session["token"])
        context = {"container_list": containers_list}
        return render(request, 'project/container_list.html', context)


def add_container(request):
    if request.session["token"]:
        if request.method == "GET" and request.session["token"]:
            return render(request, 'project/add_container.html')
        elif request.method == "POST" and request.session["token"]:
            create_container(request.session['token'], request.POST["container_name"])
            return HttpResponseRedirect(reverse('project:container'))
    else:
        error_msg = "Wrong Combination of username and password"
        messages.error(request, error_msg)
        return HttpResponseRedirect(reverse('project:index'))


def remove_container(request):
    if request.method == "POST" and request.session["token"]:
        token = request.session['token']
        container_name = request.POST["container"]
        if get_container_details(token, container_name) == []:
            delete_container(token, container_name)
            return HttpResponseRedirect(reverse('project:container'))
        else:
            return render(request, 'project/remove_container.html')


def container_detail(request, container_name):
    if request.method == "GET" and request.session["token"]:
        content_list = get_container_details(request.session["token"], container_name)
        context = {"container_name": container_name,
                   "content_list": content_list}
        return render(request, 'project/container_detail.html', context)


def add_container_content(request, container_name):
    if request.method == "GET" and request.session["token"]:
        return render(request, 'project/add_container_content.html')
    elif request.method == "POST" and request.session["token"]:
        if 'file' in request.FILES and request.FILES['file']:
            token = request.session["token"]
            file = request.FILES['file']
            create_object(token, container_name, file._name, file)
            return HttpResponseRedirect(reverse('project:container_detail', args=(container_name,)))
        else:
            messages.error(request, "Please select a file")
            return render(request, 'project/add_container_content.html')


def remove_container_content(request):
    if request.method == "POST" and request.session["token"]:
        token = request.session['token']
        container_name = request.POST["container"]
        content_name = request.POST["content"]

        delete_object(token, container_name, content_name)
        return HttpResponseRedirect(reverse('project:container_detail', args=(container_name,)))


def get_content_temp_url(request, container_name, file_name):
    if request.method == "GET" and request.session["token"]:
        token = request.session["token"]
        url = get_object_content_temp(token, container_name, file_name)
        context = {"url": url}
        return render(request, 'project/container_content_temp_url.html', context)

demo/project/templates/project/add_container.html
{% extends 'base.html' %}

{% load static %}
{% block content_block %}

<div class="list_content">
    <a href="{% url 'project:container' %}"><-- Back</a>

    <br>
    <br>
    New Container name<br>
    <form action="{% url 'project:add_container' %}" method="post">
        {% csrf_token %}
        <input type="text" name="container_name">
        <!--<input type="submit" value="Create">-->
        <button type="submit" class="btn btn-success">Create</button>
    </form>


    <br>
    <form action="{% url 'project:logout' %}" method="post">
        {% csrf_token %}
        <!--<input type="submit" value="Log out">-->
        <button type="submit" class="btn btn-info">Log out</button>
    </form>
</div>
{% endblock %}

demo/project/templates/project/add_container_content.html
{% extends 'base.html' %}

{% load static %}
{% block content_block %}

<div class="list_content">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="file">
        <br>
        <br>
        <!--<button type="submit">Upload</button>-->
        <button type="submit" class="btn btn-success">Upload</button>
    </form>

    <br>
    <form action="{% url 'project:logout' %}" method="post">
        {% csrf_token %}
        <!--<input type="submit" value="Log out">-->
        <button type="submit" class="btn btn-info">Log out</button>
    </form>
</div>
{% endblock %}

demo/project/templates/project/container_content_temp_url.html
{% extends 'base.html' %}

{% load static %}
{% block content_block %}
<div class="list_content" style="width: 100%">
    <p>This url will expire in 30 seconds:</p>
    <br>
    <a href="{{url}}">{{url}}</a>
</div>

{% endblock %}

demo/project/templates/project/container_detail.html
{% extends 'base.html' %}

{% load static %}
{% block content_block %}

<div class="list_content">
    <a href="{% url 'project:container' %}"><-- Back</a>

    <br>
    <br>

    {% for content in content_list %}
    <li class="content_list">
        {{ container_name }}/{{content}}
        <a style="float: right;" href="{% url 'project:get_content_temp_url' container_name content %}">temp_url</a>
        <form action="{% url 'project:remove_container_content' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="container" value={{ container_name }}>
            <input type="hidden" name="content" value={{ content }}>
            <!--<input type="submit" value="Delete">-->
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </li>
    {% endfor %}

    <br>

    <a class="addNew" href="{% url 'project:add_container_content' container_name%}">Upload New</a>

    <br>
    <br>
    <form action="{% url 'project:logout' %}" method="post">
        {% csrf_token %}
        <!--<input type="submit" value="Log out">-->
        <button type="submit" class="btn btn-info">Log out</button>
    </form>

</div>

{% endblock %}

demo/project/templates/project/container_list.html
{% extends 'base.html' %}

{% load static %}
{% block content_block %}


<div class="list_content">
    {% for container in container_list %}
    <li style="list-style-type:none">
        <a href="{% url 'project:container_detail' container %}">{{ container }}</a>

        <form action="{% url 'project:remove_container' %}" method="post" class="deleteButton">
            {% csrf_token %}
            <input type="hidden" name="container" value={{ container }}>
            <!--<input type="submit" value="Delete">-->
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </li>
    {% endfor %}


    <a class="addNew" href="{% url 'project:add_container' %}">Add New</a>

    <form action="{% url 'project:logout' %}" method="post">
        {% csrf_token %}
        <!--<input type="submit" value="Log out">-->
        <button type="submit" class="btn btn-info">Log out</button>
    </form>
    {% endblock %}
</div>

demo/project/templates/project/index.html
{% extends 'base.html' %}

{% load static %}
{% block content_block %}

<div class="content">
    <form action="{% url 'project:index' %}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="project_name">Project Name</label>
            <input type="text" id="project_name" name="project_name"><br>
        </div>

        <div class="form-group">
            <label for="user_name">User Name</label>
            <input type="text" id="user_name" name="user_name"><br>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" id="password" name="password"><br>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>


    </form>
</div>


{% endblock %}

demo/project/templates/project/remove_container.html
{% extends 'base.html' %}

{% load static %}
{% block content_block %}
<div class="list_content">
    <p>Please empty the container first. </p>
</div>

{% endblock %}

demo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link href="{% static 'project/all.css' %}" rel="stylesheet" type="text/css" >
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li class="msg" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% block content_block %}
{% endblock %}

</body>
</html>